In [2]:
import cv2
import numpy as np
import insightface
from insightface.app import FaceAnalysis
from insightface.data import get_image as ins_get_image
import time
import os
from numpy import arcsin
from numpy.linalg import norm
from numpy import dot
from scipy.spatial import distance


# from sklearn.metrics.pairwise import cosine_similarity

In [28]:
app = FaceAnalysis(providers=[ 'CPUExecutionProvider']) #'CUDAExecutionProvider',
app.prepare(ctx_id=0, det_size=(640, 640))

# img = ins_get_image('t1')

img = cv2.imread("C:/Users/HP/Desktop/l_front.jpg")
img = cv2.resize(img , (640,640))
faces = app.get(img , max_num=1)
embeddings = faces[0]['embedding']
rimg = app.draw_on(img, faces)
cv2.imwrite("./t1_output.jpg", rimg)

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det

True

In [29]:
len(embeddings_list) , len(embeddings)

(3, 512)

In [30]:
def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))
cos_sim(embeddings_list[0] , embeddings)


0.15384945

In [5]:
# For webcam input:
cap = cv2.VideoCapture(0)

app = FaceAnalysis(providers=[ 'CPUExecutionProvider']) #'CUDAExecutionProvider',
app.prepare(ctx_id=0, det_size=(640, 640))

start_time = int()
count_time = 0
count = 1
embeddings_list = list()
face_landmark_list = list()
user_name = 'LeeHanGyeol'

texts = ['정면을 보고 S 키를 눌러주세요.' , '오른쪽으로 얼굴을 돌리고 S를 눌러주세요.' , '왼쪽으로 얼굴을 돌리고 S를 눌러주세요.']


if user_name not in os.listdir():
  os.mkdir(f'./{user_name}')
else:
  pass

file_path = f'./{user_name}/'

while cap.isOpened():
  success, image = cap.read()

  if not success:
    print("Ignoring empty camera frame.")
    continue
  image = cv2.resize(image , (640,640))

  if count_time == 0:
    start_time = int(time.time())
  try:
      if start_time + count_time == int(time.time()):

          faces = app.get(image , max_num=1)
          face_landmark_list.append(faces[0]['landmark_2d_106'])
          embeddings_list.append(faces[0]['embedding'])
          rimg = app.draw_on(image, faces)
          cv2.imwrite( f"{file_path}{user_name}{count}.jpg", rimg)
          count_time += 10      
          count += 1
  except:
      print('error')  

  cv2.imshow('MediaPipe Face Mesh', cv2.flip(image, 1))
  if cv2.waitKey(5) & 0xFF == 27:
    cv2.destroyAllWindows()
    break
cap.release()

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det

In [19]:
def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

cos_sim()

19.62200164794922

In [14]:
embeddings_list[1]

array([ 1.13020134e+00,  1.87042654e+00, -9.62529361e-01, -3.89046252e-01,
       -3.97923321e-01, -1.16043043e+00, -3.35071832e-01,  1.21931806e-01,
       -7.82600164e-01,  7.53207207e-01,  4.41418201e-01, -3.91088635e-01,
       -1.40403807e+00,  9.37047184e-01, -1.23505914e+00,  1.36427641e+00,
        5.17026067e-01,  2.61592716e-02, -9.66342032e-01, -2.50442088e-01,
        1.28616095e+00,  4.40967262e-01,  1.07511938e+00, -1.10808432e+00,
       -6.80812895e-01, -1.10813156e-01, -7.34821260e-02,  3.71463001e-02,
       -5.83965719e-01,  1.07458323e-01, -1.48519325e+00, -8.55560303e-01,
       -5.34027040e-01,  1.29850483e+00, -7.73455977e-01, -3.07033300e-01,
       -9.82392430e-01, -8.78617048e-01, -1.78139210e-01, -8.68641615e-01,
       -8.40019345e-01, -1.03459828e-01, -1.79914415e+00,  2.41602153e-01,
       -4.92181808e-01,  1.80602893e-01, -1.10872018e+00,  2.37855360e-01,
       -1.10504076e-01, -1.05742179e-02, -6.41355366e-02, -6.16850033e-02,
        2.28546321e-01,  

In [10]:
len(embeddings_list)

3

In [27]:
# For webcam input:

## S 누르면 입력 받도록.
cap = cv2.VideoCapture(0)

app = FaceAnalysis(providers=[ 'CPUExecutionProvider']) #'CUDAExecutionProvider',
app.prepare(ctx_id=0, det_size=(640, 640))

user_name = 'LeeHanGyeol'
pos = ['front' , 'right' ,'left']
embeddings_list = list()
face_landmark = list()
face_landmark_list = list()
texts = ['Look at the camera & Press button "S" to save' , 'Turn your face to the right and press the s key.' , 'Turn your face to the left and press the s key']
count = 0

if user_name not in os.listdir():
  os.mkdir(f'./{user_name}')
else:
  pass

file_path = f'./{user_name}/'

while cap.isOpened():
  success, image = cap.read()

  if not success:
    print("Ignoring empty camera frame.")
    continue
  image = cv2.resize(image , (640,640))
  image =  cv2.flip(image, 1)
  image = cv2.putText(image, texts[count], (50,50), cv2.FONT_ITALIC, 0.7, (255,0,0), 1)

  
  key = cv2.waitKey(5)
  if key & 0xFF == 115:
    faces = app.get(image , max_num=1)
    
    rimg = app.draw_on(image, faces)
    if count == 0:  
      cv2.imwrite(f"{file_path}{user_name}_{pos[count]}.jpg", rimg)
      face_landmark_list.append(faces[0]['landmark_2d_106'])
      embeddings_list.append(faces[0]['embedding'])
      image += 200
      count += 1

    elif count == 1:
      face_landmark_list.append(faces[0]['landmark_2d_106'])
      eye_euclidean = distance.euclidean(face_landmark_list[-1][38] , face_landmark_list[-1][88])
      if face_landmark_list[0][86][0] < face_landmark_list[-1][86][0] and eye_euclidean < 50: 
        cv2.imwrite(f"{file_path}{user_name}_{pos[count]}.jpg", rimg)
        embeddings_list.append(faces[0]['embedding'])
        image += 200
        count += 1
        print('right')
      else:
        print('얼굴을 똑바로 돌리십시오.')

    elif count == 2: 
      face_landmark_list.append(faces[0]['landmark_2d_106'])
      eye_euclidean = distance.euclidean(face_landmark_list[-1][38] , face_landmark_list[-1][88])
      if face_landmark_list[0][86][0] > face_landmark_list[-1][86][0] and eye_euclidean < 50:
        cv2.imwrite(f"{file_path}{user_name}_{pos[count]}.jpg", rimg)
        embeddings_list.append(faces[0]['embedding'])
        image += 200
        count += 1
        print('left')
      else:
        print('얼굴을 똑바로 돌리십시오.')

    if count == 3:
      break  

  cv2.imshow('MediaPipe Face Mesh',image) # cv2.flip(image, 1)

  if key & 0xFF == 27:
    cv2.destroyAllWindows()
    break

cv2.destroyAllWindows()
cap.release()

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det

In [18]:
print(distance.euclidean(face_landmark_list[0][38] ,face_landmark_list[0][88])) ##눈을 이용해서 측면 검사. #38 오른눈.   88 왼눈.
print(distance.euclidean(face_landmark_list[1][38] ,face_landmark_list[1][88])) ## 눈을 이용해서 검사.
print(distance.euclidean(face_landmark_list[2][38] ,face_landmark_list[2][88]))


71.57958221435547
25.11652946472168
23.78841781616211


In [19]:
face_landmark_list[1][38] , face_landmark_list[1][88]

(array([376.65506, 311.06018], dtype=float32),
 array([401.5934 , 314.04657], dtype=float32))

In [10]:
len(embeddings_list)

0

In [90]:
#['bbox', 'kps', 'det_score', 'landmark_3d_68', 'pose', 'landmark_2d_106', 'gender', 'age', 'embedding']

array([335.7523, 347.3932], dtype=float32)

In [91]:
#['bbox', 'kps', 'det_score', 'landmark_3d_68', 'pose', 'landmark_2d_106', 'gender', 'age', 'embedding']

array([235.92891, 331.79294], dtype=float32)

In [115]:
face_landmark_list[0]

array([[317.25293, 493.70102],
       [247.662  , 335.59567],
       [260.09204, 439.6799 ],
       [264.50027, 450.70007],
       [269.73416, 461.29208],
       [276.0785 , 471.07205],
       [283.74698, 479.9116 ],
       [292.94788, 487.08572],
       [304.01224, 491.9114 ],
       [246.2804 , 347.03128],
       [245.59648, 358.5363 ],
       [245.60904, 370.1467 ],
       [246.39034, 381.84372],
       [248.00577, 393.5171 ],
       [250.45543, 405.2234 ],
       [253.17743, 416.77713],
       [256.3651 , 428.30658],
       [389.70197, 331.6208 ],
       [382.0425 , 440.9431 ],
       [377.09894, 452.22934],
       [370.99466, 462.95026],
       [363.49542, 472.74924],
       [354.3447 , 481.32248],
       [343.59232, 488.05573],
       [331.23227, 492.4159 ],
       [391.755  , 343.50522],
       [393.0865 , 355.5601 ],
       [393.68146, 367.78204],
       [393.51318, 380.04727],
       [392.61578, 392.4261 ],
       [391.00552, 404.86133],
       [388.8848 , 417.08136],
       [

IndexError: list index out of range

In [99]:
print(face_list[0][0]['landmark_2d_106'][86])
print(face_list[1][0]['landmark_2d_106'][86])
print(face_list[2][0]['landmark_2d_106'][86])

[335.7523 347.3932]
[235.92891 331.79294]
[450.4195 325.8076]


In [106]:
image.shape

(640, 640, 3)

In [2]:
# For webcam input:

## S 누르면 입력 받도록.
cap = cv2.VideoCapture(0)

app = FaceAnalysis(providers=[ 'CPUExecutionProvider']) #'CUDAExecutionProvider',
app.prepare(ctx_id=0, det_size=(640, 640))


embeddings_list = list()
face_landmark_list = list()
user_name = 'LeeHanGyeol'
texts = ['Look at the camera & Press button "S" to save' , '오른쪽으로 얼굴을 돌리고 S를 눌러주세요.' , '왼쪽으로 얼굴을 돌리고 S를 눌러주세요.']

pos = ['front' , 'right' ,'left']
count = 0
num = 0


if user_name not in os.listdir():
  os.mkdir(f'./{user_name}')
else:
  pass

file_path = f'./{user_name}/'

while cap.isOpened():
  success, image = cap.read()

  if not success:
    print("Ignoring empty camera frame.")
    continue
  image = cv2.resize(image , (640,640))
  image =  cv2.flip(image, 1)
  image = cv2.putText(image, texts[count], (50,50), cv2.FONT_ITALIC, 1, (255,0,0), 2)
  
  cv2.imshow('MediaPipe Face Mesh',image)

  key = cv2.waitKey(5)
  
  if key == ord('s'):
      cv2.imwrite(f'{file_path}/{user_name}{pos[num]}.jpg', image)
      num += 1
      print('Saved')
      continue

  elif key & 0xFF == 27:
    cv2.destroyAllWindows()
    break

cap.release()

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\HP/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det